version: '2'

services:
    multichain:
        container_name: multichain
        build: ./multichain/node
        env_file:
            - ./multichain/node/env

    node-client:
        container_name: node-client
        build: ./node-client
        ports:
            - 80:3002
        depends_on:
            - multichain
        env_file:
            - ./node-client/.env

    mqtt:
        container_name: mqtt
        image: eclipse-mosquitto:latest
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        ports:
            - 1883:1883
        depends_on:
            - multichain

    grafana:
        image: grafana/grafana
        ports:
                - 3000:3000
        depends_on:
                - node-client
        environment:
                - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource

