version: '2'

services:
    multichain:
        container_name: multichain
        build: ./docker-multichain/master
        env_file:
            - ./docker-multichain/master/env

    node-master:
        container_name: node-master
        build: ./multichain-node
        ports:
            - 3001:3001
        env_file:
            - ./multichain-node/.env
        depends_on:
            - mqtt

    node-client:
        container_name: node-client
        build: ./node-client
        ports:
            - 80:3002
        env_file:
            - ./node-client/.env
        depends_on:
            - multichain

    mqtt:
        container_name: mqtt
        image: eclipse-mosquitto
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        ports:
            - 1883:1883
        depends_on:
            - multichain
