version: '2'

services:
        multichain:
                container_name: multichain
                build: ./docker-multichain/master
                env_file:
                        - ./docker-multichain/master/env

        node-app:
                container_name: node-app
                build: ./multichain-node
                ports:
                        - 80:3113
                depends_on:
                        - mqtt

        mqtt:
                container_name: mqtt
                image: eclipse-mosquitto
                volumes: 
                        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
                ports:
                        - 1883:1883
                depends_on:
                        - multichain

